### ISSUE TITLE
Ideas for LibSVM wrapper

### ISSUE THREAD

**Issue by UserAB1236872** [maciejkula/rustlearn#12]
I've been internally using a LibSVM wrapper internally for my grad work, which I just put on Github to maybe provoke some design ideas:

https://github.com/Jragonmiris/rust-libsvm/tree/master/src

I like the way it turned out, except the serialization which is a bit hacky. It has a bit more of an API surface area than your implementation, and would require editing to deal with your traits, but I like the way I handled Kernel and SVM Type parameters, which exist as an Enum instead of allowing you to set unrelated hyperparams.

**Comment by maciejkula** [comment]
I really like the `enum` approach, it is quite clean. How does it handle default parameters? It would be great if we could use it while supplying sensible default hyperparam values.

**Comment by UserAB1236872** [comment]
I think I implement `default::Default`, but I don't recall if it goes to any sensible value, it may just be a zero type.

Still, there's nothing stopping some sort of better `default` method from being implemented.

**Comment by maciejkula** [comment]
Sure, I'd be happy to see a more sensible hyperparam approach.
