### ISSUE TITLE
Try to keep consistent in Array::from() method

### ISSUE THREAD

**Issue by libratiger** [maciejkula/rustlearn#21]
when the input is a `Vec<f32>` or a `Vec<Vec<f32>>`,  one uses move, the another uses reference, this is not consistent.

This is for performance, but make this clearly in docs is better.

``` rust
let array = Array::from(vec![0.0, 1.0, 2.0, 3.0]);
let array = Array::from(&vec![vec![0.0, 1.0],
                              vec![2.0, 3.0]]);
```

**Comment by maciejkula** [comment]
Can you please make a PR for the docs?
