### ISSUE TITLE
Unable to deserialize Random Forest model

### ISSUE THREAD

**Issue by insanitybit** [maciejkula/rustlearn#31]
After fitting a model I serialize it to the disk using rustc_serialize json.

I then try to load the model but I get a parse error. The reason is that the 'rng' field of the model looks like this:

... ,"feature_types":[],"rng":},{"dim":4 ...

That is, some normal fields, then the rng field, a colon, and nothing - the object just closes.

Using rustc_serialize = "0.3.*"

rustc -V
rustc 1.13.0-nightly (3c5a0fa45 2016-08-22)

The following functions are used to load and store the random forest.

```
pub fn serialize_to_file<T>(s: &T, path: &str)
    where T: Encodable
{
    let serialized = json::encode(&s).unwrap();

    let mut f = File::create(path).unwrap();
    write!(f, "{}", serialized).unwrap();
    f.flush().unwrap();
}

pub fn load_json<T: Decodable>(path: &str) -> T {
    let mut f = File::open(path).unwrap();
    let mut json_str = String::new();

    let _ = f.read_to_string(&mut json_str).unwrap();
    json::decode(&json_str).unwrap()
}
```

**Comment by maciejkula** [comment]
Should be fixed in #32, thanks for reporting it!
